In [1]:
# 모듈 설치
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


# 데이터를 처리하기 위한 모듈
## (1) numpy
* 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 패키지
* 루프를 사용하지 않고 대량 데이터의 배열 연산이 가능
* 데이터분석, AI 분야 뿐만 아니라 자연과학, 공항에서도 널리 사용

In [2]:
import numpy as np  # numpy 행 열 구조

In [3]:
array1 = np.array([1,2,3,4,5])    # array는 한가지 자료형만 저장이 가능
print(array1, type(array1))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [4]:
array2 = np.array(1, 2.3, "45", True)
print(array2, type(array2))

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [ ]:
array1.shape  # (행, 열) 행의 개수와 열은 첫번째 열은 0으로 빈간으로 나온다

(5,)

In [ ]:
array3 = np.array([[1,2,3],[4,5,6]])
print(array3, array3.shape)

[[1 2 3]
 [4 5 6]] (2, 3)


In [ ]:
array4 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(array4, array4.shape)  #(2면, 2행, 3열)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] (2, 2, 3)


In [ ]:
print('array1 : {0}차원, array3 : {1}차원, array4 : {2}차원'.format(array1.ndim,array3.ndim,array4.ndim))

array1 : 1차원, array3 : 2차원, array4 : 3차원


In [ ]:
# array 생성하는 함수
array1 = np.arange(10)
print(array1, array1.shape)

[0 1 2 3 4 5 6 7 8 9] (10,)


In [ ]:
array3 = array1.reshape(5,2)  # 해당하는 데이터를 맞춰 줘야 가능
print(array3, array3.shape)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] (5, 2)


In [ ]:
array4 = array1.reshape(-1,5)  # 행이나 열 고정할때 -1사용
print(array4, array4.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]] (2, 5)


In [ ]:
# 인덱싱과 슬라이싱
array1 = np.arange(12)
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
array1[5]

np.int64(5)

In [ ]:
arr2 = array1.reshape(-1,4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
arr2[1]

array([4, 5, 6, 7])

In [ ]:
arr2[-1, -2]    # 2차원 구조는 , 로 구분한다

np.int64(10)

In [ ]:
# 슬라이싱
arr2[:1, :3]

array([[0, 1, 2]])

In [ ]:
arr2[1: , 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
arr3 = np.arange(100)
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
arr3[30::-1]   # 앞에는 시작하는 숫자 :: 뒤에는 정해진 숫자 만큼 건너 뛴다 , -1은 역순으로 불러온다

array([30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14,
       13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

## (2) pandas 패키지
* 데이터 셋을 다루는 라이브러리
* 1차원 배열 형태는 시리즈(Series)
* 2차원 배열 형태는 데이터프레임(Data Frame)

In [ ]:
# pandas 설치
%pip install pandas

   ---------------------------------------- 0.0/11.6 MB ? eta -:--:--
   - -------------------------------------- 0.3/11.6 MB 10.6 MB/s eta 0:00:02
   --- ------------------------------------ 1.1/11.6 MB 14.2 MB/s eta 0:00:01
   -------- ------------------------------- 2.4/11.6 MB 19.0 MB/s eta 0:00:01
   --------------- ------------------------ 4.4/11.6 MB 25.4 MB/s eta 0:00:01
   ------------------------- -------------- 7.5/11.6 MB 34.1 MB/s eta 0:00:01
   ---------------------------------------  11.6/11.6 MB 59.5 MB/s eta 0:00:01
   ---------------------------------------- 11.6/11.6 MB 50.4 MB/s eta 0:00:00
   ---------------------------------------- 0.0/505.5 kB ? eta -:--:--
   --------------------------------------- 505.5/505.5 kB 33.0 MB/s eta 0:00:00
   ---------------------------------------- 0.0/345.4 kB ? eta -:--:--
   ---------------------------------------- 345.4/345.4 kB ? eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
# pandas 임포트
import pandas as pd

# 버전 확인
print(pd.__version__)

2.2.2


In [ ]:
# Series 만들기
data1 = ['a','b','c','d','e','f']                   # 리스트 생성
print("Data Type : ", type(data1), "\n", data1)
sr1 = pd.Series(data1)                              # 시리즈 생성
print("Data Type : ", type(sr1), "\n", sr1)

Data Type :  <class 'list'> 
 ['a', 'b', 'c', 'd', 'e', 'f']
Data Type :  <class 'pandas.core.series.Series'> 
 0    a
1    b
2    c
3    d
4    e
5    f
dtype: object


In [ ]:
data2 = [1,2,3,4,5,6]
sr2 = pd.Series(data2)
sr2

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [ ]:
data3 = [7,'g',True,8.1,9,'h']
sr3 = pd.Series(data3)
sr3

0       7
1       g
2    True
3     8.1
4       9
5       h
dtype: object

In [ ]:
# 인덱싱
sr1.loc[1]

'b'

In [ ]:
# 슬라이싱
sr1.loc[1:3]   # 뒤에 숫자 -1안하고 포함

1    b
2    c
3    d
dtype: object

In [ ]:
# 데이터 프레임 만들때는 딕셔너리로 만들어야 한다.
dic1 = {'col1':sr1, 'col2':sr2, 'col3':sr3}             # 딕셔너리 생성
print("Data Type : ", type(dic1), "\n", dic1)
df1 = pd.DataFrame(dic1)                                # 데이터 프레임 생성
print("Data Type : ", type(df1), "\n", df1)

Data Type :  <class 'dict'> 
 {'col1': 0    a
1    b
2    c
3    d
4    e
5    f
dtype: object, 'col2': 0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64, 'col3': 0       7
1       g
2    True
3     8.1
4       9
5       h
dtype: object}
Data Type :  <class 'pandas.core.frame.DataFrame'> 
   col1  col2  col3
0    a     1     7
1    b     2     g
2    c     3  True
3    d     4   8.1
4    e     5     9
5    f     6     h


In [ ]:
# print 안쓰고 그냥 출력했을때
df1

col1  col2  col3
0    a     1     7
1    b     2     g
2    c     3  True
3    d     4   8.1
4    e     5     9
5    f     6     h

In [ ]:
# 데이터 프레임 컬럼 조작
print(df1.columns)                               # 데이터프레임.colums 는 데이터 프레임 컬럼 정보를 가지고 있다
df1.columns = ['String', 'Number', 'Mix']        # 바꿀 컬럼을 순서대로 입력한다
df1

Index(['col1', 'col2', 'col3'], dtype='object')


String  Number   Mix
0      a       1     7
1      b       2     g
2      c       3  True
3      d       4   8.1
4      e       5     9
5      f       6     h

In [ ]:
# 데이터프레임에 인덱스 변경 가능하다
print(df1.index)                                    # 데이터 프레임 인덱스 출력
df1.index = ['r1', 'r2', 'r3', 'r4', 'r5', 'r6']    # 변경할 인텍스 순서대로 입력
df1

RangeIndex(start=0, stop=6, step=1)


String  Number   Mix
r1      a       1     7
r2      b       2     g
r3      c       3  True
r4      d       4   8.1
r5      e       5     9
r6      f       6     h

In [ ]:
# 데이터프레임 인덱싱, 슬라이싱
df1.loc['r3', 'Number']

np.int64(3)

In [ ]:
# 값만 찍고 싶은면 print 저장되는건 값만 저장됨
print(df1.loc['r3', 'Number'])

3


In [ ]:
df1.loc['r2':'r5','String':'Mix']

String  Number   Mix
r2      b       2     g
r3      c       3  True
r4      d       4   8.1
r5      e       5     9

In [ ]:
df1.loc['r2':'r5']

String  Number   Mix
r2      b       2     g
r3      c       3  True
r4      d       4   8.1
r5      e       5     9

In [ ]:
df1.loc['r2':'r5',]

String  Number   Mix
r2      b       2     g
r3      c       3  True
r4      d       4   8.1
r5      e       5     9

In [ ]:
df1.loc['r2':'r4',:'Number']

String  Number
r2      b       2
r3      c       3
r4      d       4

In [ ]:
# openpyxl 설치
%pip install openpyxl

   ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
   ------ --------------------------------- 41.0/250.9 kB 1.9 MB/s eta 0:00:01
   ---------------------------------------- 250.9/250.9 kB 3.8 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
# 파일을 데이터프레임으로 저장(Excel)
student_data = pd.read_excel('학생명단.xlsx')
student_data

이름 성별  나이      주소           전화번호  국어  영어  수학
0   유영식  남  46   대전 중구  010-1234-5678  91  82  73
1   구본우  남  25   대전 동구  010-1234-7896  82  93  74
2   김민환  남  25   대전 서구  010-1234-4567  71  85  78
3   심서연  여  25  대전 유성구  010-4567-1254  83  85  88
4   원유정  여  25  대전 대덕구  010-4575-8525  91  82  42
5   윤병윤  남  25  대전 대덕구  010-4575-8525  82  93  82
6   유연수  남  25  대전 대덕구  010-4575-8525  71  75  75
7    윤진  여  25  대전 대덕구  010-4575-8525  83  85  65
8   이종문  남  25  대전 대덕구  010-4575-8525  91  73  85
9   이준영  남  25  대전 대덕구  010-4575-8525  82  85  88
10  조현정  여  25  대전 대덕구  010-4575-8525  71  99  77

In [ ]:
# 파일을 데이터프레임으로 저장 (텍스트파일(txt or csv))
daejeon_data = pd.read_csv('대전광역시.txt', delimiter='|', encoding='utf-8')
daejeon_data

우편번호     시도     시도영문  시군구       시군구영문  읍면  읍면영문         도로명코드  \
0       34316  대전광역시  Daejeon  대덕구  Daedeok-gu NaN   NaN  302303010005   
1       34316  대전광역시  Daejeon  대덕구  Daedeok-gu NaN   NaN  302303010005   
2       34316  대전광역시  Daejeon  대덕구  Daedeok-gu NaN   NaN  302303010005   
3       34316  대전광역시  Daejeon  대덕구  Daedeok-gu NaN   NaN  302303010005   
4       34316  대전광역시  Daejeon  대덕구  Daedeok-gu NaN   NaN  302303010005   
...       ...    ...      ...  ...         ...  ..   ...           ...   
113326  35067  대전광역시  Daejeon   중구     Jung-gu NaN   NaN  301404295267   
113327  35067  대전광역시  Daejeon   중구     Jung-gu NaN   NaN  301404295267   
113328  35067  대전광역시  Daejeon   중구     Jung-gu NaN   NaN  301404295267   
113329  35065  대전광역시  Daejeon   중구     Jung-gu NaN   NaN  301404295268   
113330  35066  대전광역시  Daejeon   중구     Jung-gu NaN   NaN  301404295263   

            도로명               도로명영문  ...       법정동코드  법정동명  리명  행정동명  산여부  \
0         대청호수로    Daecheonghosu-ro  ...  3023012100   갈전동 NaN  신탄진동    0   
1         대청호수로    Daecheonghosu-ro  ...  3023012100   갈전동 NaN  신탄진동    0   
2         대청호수로    Daecheonghosu-ro  ...  3023012100   갈전동 NaN  신탄진동    0   
3         대청호수로    Daecheonghosu-ro  ...  3023012100   갈전동 NaN  신탄진동    0   
4         대청호수로    Daecheonghosu-ro  ...  3023012100   갈전동 NaN  신탄진동    0   
...         ...                 ...  ...         ...   ...  ..   ...  ...   
113326   모암로7번길   Moam-ro 7beon-gil  ...  3014010800    호동 NaN   석교동    0   
113327   모암로7번길   Moam-ro 7beon-gil  ...  3014010800    호동 NaN   석교동    0   
113328   모암로7번길   Moam-ro 7beon-gil  ...  3014010800    호동 NaN   석교동    0   
113329   모암로8번길   Moam-ro 8beon-gil  ...  3014010800    호동 NaN   석교동    0   
113330  모암로24번길  Moam-ro 24beon-gil  ...  3014010800    호동 NaN   석교동    0   

       지번본번  읍면동일련번호 지번부번  구우편번호 우편번호일련번호  
0       238        2    8    NaN      NaN  
1       503        2    0    NaN      NaN  
2       498        2    0    NaN      NaN  
3       238        2    7    NaN      NaN  
4       238        2    2    NaN      NaN  
...     ...      ...  ...    ...      ...  
113326   24        1    2    NaN      NaN  
113327   24        1   21    NaN      NaN  
113328   24        1    2    NaN      NaN  
113329   12        2    2    NaN      NaN  
113330   21        2    4    NaN      NaN  

[113331 rows x 26 columns]

In [ ]:
# 데이터 프레임 정보 확인
student_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   이름      11 non-null     object
 1   성별      11 non-null     object
 2   나이      11 non-null     int64 
 3   주소      11 non-null     object
 4   전화번호    11 non-null     object
 5   국어      11 non-null     int64 
 6   영어      11 non-null     int64 
 7   수학      11 non-null     int64 
dtypes: int64(4), object(4)
memory usage: 836.0+ bytes


In [ ]:
daejeon_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113331 entries, 0 to 113330
Data columns (total 26 columns):
 #   Column    Non-Null Count   Dtype  
---  ------    --------------   -----  
 0   우편번호      113331 non-null  int64  
 1   시도        113331 non-null  object 
 2   시도영문      113331 non-null  object 
 3   시군구       113331 non-null  object 
 4   시군구영문     113331 non-null  object 
 5   읍면        0 non-null       float64
 6   읍면영문      0 non-null       float64
 7   도로명코드     113331 non-null  int64  
 8   도로명       113331 non-null  object 
 9   도로명영문     113331 non-null  object 
 10  지하여부      113331 non-null  int64  
 11  건물번호본번    113331 non-null  int64  
 12  건물번호부번    113331 non-null  int64  
 13  건물관리번호    113331 non-null  object 
 14  다량배달처명    0 non-null       float64
 15  시군구용건물명   10968 non-null   object 
 16  법정동코드     113331 non-null  int64  
 17  법정동명      113331 non-null  object 
 18  리명        0 non-null       float64
 19  행정동명      110898 non-null  object 
 20  산여부 

In [ ]:
student_data.describe()    # 숫자만 나옴
# count 갯수
# mean 평균
# std 표준편차
# min 최소
# 25% 1/4 분위
# 50% 2/4 분위 or 중앙값(median)
# 75% 3/4 분위
# max 최대

나이         국어         영어         수학
count  11.000000  11.000000  11.000000  11.000000
mean   26.909091  81.636364  85.181818  75.181818
std     6.331738   7.788103   7.652688  13.013978
min    25.000000  71.000000  73.000000  42.000000
25%    25.000000  76.500000  82.000000  73.500000
50%    25.000000  82.000000  85.000000  77.000000
75%    25.000000  87.000000  89.000000  83.500000
max    46.000000  91.000000  99.000000  88.000000

In [ ]:
daejeon_data.describe()

In [ ]:
student_data

이름 성별  나이      주소           전화번호  국어  영어  수학
0   유영식  남  46   대전 중구  010-1234-5678  91  82  73
1   구본우  남  25   대전 동구  010-1234-7896  82  93  74
2   김민환  남  25   대전 서구  010-1234-4567  71  85  78
3   심서연  여  25  대전 유성구  010-4567-1254  83  85  88
4   원유정  여  25  대전 대덕구  010-4575-8525  91  82  42
5   윤병윤  남  25  대전 대덕구  010-4575-8525  82  93  82
6   유연수  남  25  대전 대덕구  010-4575-8525  71  75  75
7    윤진  여  25  대전 대덕구  010-4575-8525  83  85  65
8   이종문  남  25  대전 대덕구  010-4575-8525  91  73  85
9   이준영  남  25  대전 대덕구  010-4575-8525  82  85  88
10  조현정  여  25  대전 대덕구  010-4575-8525  71  99  77

In [ ]:
student_data.loc[:, ('이름', '국어', '영어', '수학')]

이름  국어  영어  수학
0   유영식  91  82  73
1   구본우  82  93  74
2   김민환  71  85  78
3   심서연  83  85  88
4   원유정  91  82  42
5   윤병윤  82  93  82
6   유연수  71  75  75
7    윤진  83  85  65
8   이종문  91  73  85
9   이준영  82  85  88
10  조현정  71  99  77

In [ ]:
daejeon_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113331 entries, 0 to 113330
Data columns (total 26 columns):
 #   Column    Non-Null Count   Dtype  
---  ------    --------------   -----  
 0   우편번호      113331 non-null  int64  
 1   시도        113331 non-null  object 
 2   시도영문      113331 non-null  object 
 3   시군구       113331 non-null  object 
 4   시군구영문     113331 non-null  object 
 5   읍면        0 non-null       float64
 6   읍면영문      0 non-null       float64
 7   도로명코드     113331 non-null  int64  
 8   도로명       113331 non-null  object 
 9   도로명영문     113331 non-null  object 
 10  지하여부      113331 non-null  int64  
 11  건물번호본번    113331 non-null  int64  
 12  건물번호부번    113331 non-null  int64  
 13  건물관리번호    113331 non-null  object 
 14  다량배달처명    0 non-null       float64
 15  시군구용건물명   10968 non-null   object 
 16  법정동코드     113331 non-null  int64  
 17  법정동명      113331 non-null  object 
 18  리명        0 non-null       float64
 19  행정동명      110898 non-null  object 
 20  산여부 

In [ ]:
daejeon_data = daejeon_data.loc[:,('우편번호','시도','시군구','도로명','법정동명','행정동명')]
daejeon_data

우편번호     시도  시군구      도로명 법정동명  행정동명
0       34316  대전광역시  대덕구    대청호수로  갈전동  신탄진동
1       34316  대전광역시  대덕구    대청호수로  갈전동  신탄진동
2       34316  대전광역시  대덕구    대청호수로  갈전동  신탄진동
3       34316  대전광역시  대덕구    대청호수로  갈전동  신탄진동
4       34316  대전광역시  대덕구    대청호수로  갈전동  신탄진동
...       ...    ...  ...      ...  ...   ...
113326  35067  대전광역시   중구   모암로7번길   호동   석교동
113327  35067  대전광역시   중구   모암로7번길   호동   석교동
113328  35067  대전광역시   중구   모암로7번길   호동   석교동
113329  35065  대전광역시   중구   모암로8번길   호동   석교동
113330  35066  대전광역시   중구  모암로24번길   호동   석교동

[113331 rows x 6 columns]